name: OpsDev-CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: npm test
      - name: Archive Unit test results
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: junit.xml
